name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    name: Build and Test on ${{ matrix.runner }} with Rust ${{ matrix.rust }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        rust:
          - 1.82.0
          - stable
          - beta

    steps:
      - name: Install OpenSSL
        run: sudo apt-get install -y libssl-dev

      - name: Install Clang
        run: sudo apt-get install -y clang

      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Toolchain
        run: |
          rustup toolchain install \
            --no-self-update \
            --profile default \
            ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}

      - name: Check Style
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Test
        run: |
          ROOT_KEYSTORE="${GITHUB_WORKSPACE}/root_keystore.p12" cargo test --all

      - name: Build
        run: |
          cargo build --release
