name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test_x64:
    name: Build and Test on x64 ${{ matrix.rust }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rust:
          - stable
          - beta

    steps:
      - name: Install YAJL
        run: sudo apt-get install -y libyajl-dev
        continue-on-error: true

      - name: Install OpenSSL
        run: sudo apt-get install -y libssl-dev

      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Display Toolchain Information
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Test
        run: |
          cargo check
          ROOT_KEYSTORE="${GITHUB_WORKSPACE}/root_keystore.p12" cargo test --all

      - name: Build
        run: |
          cargo build --release

  build_and_test_aarch64:
    name: Build and Test on aarch64 ${{ matrix.rust }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rust:
          - stable
          - beta
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: aarch64-unknown-linux-gnu
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-gnu --release
