name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
        rust:
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install YAJL
        run: sudo apt-get install -y libyajl-dev
        continue-on-error: true

      - name: Install OpenSSL
        run: sudo apt-get install -y libssl-dev

      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Display Toolchain Information
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Test
        run: |
          cargo check
          ROOT_KEYSTORE="${GITHUB_WORKSPACE}/root_keystore.p12" cargo test --all

      - name: Build
        run: |
          cargo build --release
