on:
  push:
    tags:
      - "*"
  workflow_dispatch:

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Publish
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CRATES_API_TOKEN }}
